services:
  # MongoDB Service
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  # Spring Boot Backend Service
  backend:
    image: my-app:1.0  
    container_name: springboot-backend
    ports:
      - "8081:8080"
    depends_on:
      - mongo  # Ensure MongoDB is started before Spring Boot
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:pass@mongo:27018/todoapp?authSource=admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
